const assert = require("assert");
const { ObjectId } = require("mongodb");
const { getOutcomeLearningInstruction: rule } = require("../learning/outcomeLearningRuleEngine");
const event = Object.freeze({ eventId: "e", eventType: "Attend", childId: "c", activityId: "a", bookingId: "b", occurredAt: "2026-09-20T00:00:00Z" });
const context = Object.freeze({ status: "APPLICABLE", activityId: "a", outcomeIds: Object.freeze(["x", "y"]) });
const result = rule(event, context);
assert.deepStrictEqual(result, { status: "APPLICABLE", reasonCode: "OUTCOME_LEARNING_RULE_APPLIED", eventId: "e", eventType: "Attend", childId: "c", activityId: "a", learning: { scoreDelta: 0.10, confidenceDelta: 0.05, evidenceIncrement: 1 }, outcomeIds: ["x", "y"], rule: { ruleType: "VERIFIED_ATTENDANCE_EXPOSURE", version: 1 } });
assert(!(result instanceof Promise));
assert.deepStrictEqual(rule(event, context), result);
result.outcomeIds.push("z");
assert.deepStrictEqual(context.outcomeIds, ["x", "y"]);
for (const eventType of ["View", "Click", "Save", "Unsave", "Dismiss", "Book", "Rate", "Complete"]) assert.strictEqual(rule({ ...event, eventType }, context).reasonCode, "UNSUPPORTED_OUTCOME_EVENT");
for (const input of [null, undefined, [], 1, {}, { ...event, bookingId: null }, { ...event, occurredAt: "bad" }]) assert.strictEqual(rule(input, context).status, "NOT_APPLICABLE");
for (const ctx of [null, [], {}, { ...context, activityId: "other" }, { ...context, outcomeIds: [null] }, { ...context, outcomeIds: ["x", "x"] }]) assert.strictEqual(rule(event, ctx).reasonCode, "INVALID_CONTEXT");
const id = new ObjectId();
assert.strictEqual(rule(event, { ...context, outcomeIds: [id, id.toHexString()] }).reasonCode, "INVALID_CONTEXT");
for (const ctx of [{ ...context, outcomeIds: [] }, { status: "NOT_APPLICABLE", reasonCode: "NO_MAPPED_OUTCOMES" }]) assert.strictEqual(rule(event, ctx).reasonCode, "NO_MAPPED_OUTCOMES");
assert.deepStrictEqual(rule(event, { ...context, weight: 500, evidenceGuidance: "anything" }).learning, { scoreDelta: 0.1, confidenceDelta: 0.05, evidenceIncrement: 1 });
console.log("Outcome learning rule engine unit tests: PASSED");
