const D1_EVALUATION_STATUS = Object.freeze({
    RESOLVED: "RESOLVED",
    UNRESOLVABLE: "UNRESOLVABLE"
});

const D1_APPLICABILITY = Object.freeze({
    APPLICABLE: "APPLICABLE",
    NOT_APPLICABLE: "NOT_APPLICABLE"
});

const D1_COVERAGE = Object.freeze({
    AVAILABLE: "AVAILABLE",
    PARTIAL: "PARTIAL",
    MISSING: "MISSING"
});

const D1_SUFFICIENCY = Object.freeze({
    SUFFICIENT: "SUFFICIENT",
    UNCERTAIN: "UNCERTAIN",
    INSUFFICIENT: "INSUFFICIENT",
    BLOCKED: "BLOCKED"
});

const D1_EXPERIENCE_COMPARISON = Object.freeze({
    MATCH: "MATCH",
    MISMATCH: "MISMATCH",
    UNAVAILABLE: "UNAVAILABLE"
});

const D1_RESOLVER = Object.freeze({
    PARENT: "PARENT",
    CHILD_BEHAVIOR: "CHILD_BEHAVIOR",
    CATALOG: "CATALOG",
    SYSTEM_DATA: "SYSTEM_DATA",
    UNKNOWN: "UNKNOWN"
});

const D1_EVIDENCE_NATURE = Object.freeze({
    DIRECT: "DIRECT",
    DERIVED: "DERIVED",
    CONTEXTUAL: "CONTEXTUAL"
});

const D1_PROVENANCE_STRENGTH = Object.freeze({
    ID_PROVEN: "ID_PROVEN",
    RULE_DERIVED: "RULE_DERIVED",
    UNKNOWN: "UNKNOWN"
});

const MIN_CORROBORATING_NON_PASSIVE_EVENTS = 2;

module.exports = {
    D1_EVALUATION_STATUS,
    D1_APPLICABILITY,
    D1_COVERAGE,
    D1_SUFFICIENCY,
    D1_EXPERIENCE_COMPARISON,
    D1_RESOLVER,
    D1_EVIDENCE_NATURE,
    D1_PROVENANCE_STRENGTH,
    MIN_CORROBORATING_NON_PASSIVE_EVENTS
};
